"""Sorted PMI decay plot for top-coactivation artifacts."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import torch

from analysis.io import analysis_output_dirs, write_csv, write_json
from analysis.style import BLUE, BLUE_LIGHT, FIGSIZE_WIDE, INK, INK_MUTED, SERIES2, configure_matplotlib, save_figure, styled_legend
from .data import TopCoactivationArtifact, load_top_coactivation

SUITE_NAME = "coactivation-distributions"
DEFAULT_QUANTILES = (0.01, 0.10, 0.50, 0.90, 0.99)


@dataclass(frozen=True)
class SortedPmiDecayResult:
    """Paths and summary generated by the sorted PMI decay plot."""

    figure_path: Path
    summary_path: Path
    table_path: Path
    summary: dict[str, object]


def plot_sorted_pmi_decay(
    run_root: str | Path,
    *,
    output_root: str | Path | None = None,
    quantiles: Sequence[float] = DEFAULT_QUANTILES,
) -> SortedPmiDecayResult:
    """Generate a rank-decay plot after sorting each target's coacts by PMI."""

    artifact = load_top_coactivation(run_root)
    if artifact.mode != "pmi":
        raise ValueError(f"sorted PMI decay requires mode='pmi', got {artifact.mode!r}")

    stats = compute_sorted_pmi_decay(artifact.top_values, quantiles=quantiles)
    output_dirs = analysis_output_dirs(run_root, SUITE_NAME, output_root=output_root)

    figure_path = output_dirs["figures"] / "sorted-pmi-decay.png"
    table_path = output_dirs["tables"] / "sorted-pmi-decay.csv"
    summary_path = output_dirs["summaries"] / "sorted-pmi-decay.json"

    _write_plot(figure_path, stats)
    _write_table(table_path, stats)
    summary = _build_summary(artifact, stats)
    write_json(summary_path, summary)

    return SortedPmiDecayResult(
        figure_path=figure_path,
        summary_path=summary_path,
        table_path=table_path,
        summary=summary,
    )


def compute_sorted_pmi_decay(
    top_values: torch.Tensor,
    *,
    quantiles: Sequence[float] = DEFAULT_QUANTILES,
) -> dict[str, object]:
    """Compute rank-wise means and quantiles after per-target PMI sorting."""

    if top_values.ndim != 3:
        raise ValueError("top_values must have shape [components, d_sae, top_k]")
    if not quantiles:
        raise ValueError("at least one quantile is required")
    if any(q < 0.0 or q > 1.0 for q in quantiles):
        raise ValueError("quantiles must be between 0 and 1")

    values = top_values.detach().cpu().to(torch.float32)
    top_k = int(values.shape[-1])
    flat = values.reshape(-1, top_k)

    # The saved order is reducer top-K order before PMI post-processing. Sort
    # again so rank 1 means strongest PMI coactivation for every target latent.
    sorted_values = flat.sort(dim=1, descending=True).values
    q_tensor = torch.tensor(list(quantiles), dtype=torch.float32)
    rank_quantiles = torch.empty((len(quantiles), top_k), dtype=torch.float32)
    for rank_idx in range(top_k):
        rank_quantiles[:, rank_idx] = torch.quantile(
            sorted_values[:, rank_idx].contiguous(),
            q_tensor,
        )

    return {
        "ranks": list(range(1, top_k + 1)),
        "mean": sorted_values.mean(dim=0).tolist(),
        "quantiles": {
            _quantile_key(q): rank_quantiles[idx].tolist()
            for idx, q in enumerate(quantiles)
        },
        "num_targets": int(flat.shape[0]),
        "top_k": top_k,
        "source_score_min": float(values.min().item()),
        "source_score_max": float(values.max().item()),
    }


def _write_plot(path: Path, stats: dict[str, object]) -> None:
    plt = configure_matplotlib()
    ranks = stats["ranks"]
    quantiles = stats["quantiles"]
    assert isinstance(ranks, list)
    assert isinstance(quantiles, dict)

    p50 = quantiles.get("p50")
    p10 = quantiles.get("p10")
    p90 = quantiles.get("p90")
    p01 = quantiles.get("p01")
    p99 = quantiles.get("p99")
    mean = stats["mean"]

    fig, ax = plt.subplots(figsize=FIGSIZE_WIDE)
    if p01 is not None and p99 is not None:
        ax.fill_between(ranks, p01, p99, color=BLUE_LIGHT, alpha=0.18, linewidth=0, label="p01-p99")
    if p10 is not None and p90 is not None:
        ax.fill_between(ranks, p10, p90, color=BLUE, alpha=0.28, linewidth=0, label="p10-p90")
    if p50 is not None:
        ax.plot(ranks, p50, color=INK, linewidth=2.2, label="median")
    ax.plot(ranks, mean, color=SERIES2[1], linewidth=1.4, linestyle="--", label="mean")

    ax.axhline(0.0, color=INK_MUTED, linewidth=0.9)
    ax.set_title("Sorted Coactivation PMI Decay")
    ax.set_xlabel("Coactivation rank after sorting by PMI")
    ax.set_ylabel("PMI score")
    ax.set_xlim(1, max(ranks))
    styled_legend(ax, loc="upper right")
    save_figure(fig, path)


def _write_table(path: Path, stats: dict[str, object]) -> None:
    ranks = stats["ranks"]
    quantiles = stats["quantiles"]
    mean = stats["mean"]
    assert isinstance(ranks, list)
    assert isinstance(quantiles, dict)
    assert isinstance(mean, list)

    quantile_keys = sorted(quantiles.keys(), key=_quantile_sort_key)
    fieldnames = ["rank", "mean", *quantile_keys]
    rows = []
    for idx, rank in enumerate(ranks):
        row = {"rank": rank, "mean": mean[idx]}
        for key in quantile_keys:
            row[key] = quantiles[key][idx]
        rows.append(row)
    write_csv(path, rows, fieldnames)


def _build_summary(artifact: TopCoactivationArtifact, stats: dict[str, object]) -> dict[str, object]:
    ranks = stats["ranks"]
    quantiles = stats["quantiles"]
    mean = stats["mean"]
    assert isinstance(ranks, list)
    assert isinstance(quantiles, dict)
    assert isinstance(mean, list)

    rank_summaries = {}
    for rank in (1, 5, 10, 32, 64, 128):
        if rank <= len(ranks):
            idx = rank - 1
            rank_summaries[str(rank)] = {
                "mean": mean[idx],
                **{
                    key: values[idx]
                    for key, values in quantiles.items()
                },
            }

    return {
        "artifact_path": str(artifact.path),
        "mode": artifact.mode,
        "shape": list(artifact.shape),
        "num_targets": artifact.num_targets,
        "top_k": artifact.top_k,
        "total_tokens_processed": artifact.total_tokens_processed,
        "source_score_min": stats["source_score_min"],
        "source_score_max": stats["source_score_max"],
        "rank_summaries": rank_summaries,
    }


def _quantile_key(value: float) -> str:
    return f"p{int(round(value * 100)):02d}"


def _quantile_sort_key(key: str) -> int:
    if key.startswith("p") and key[1:].isdigit():
        return int(key[1:])
    return 10_000

